### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by vicb** [chiotas/clouds-horizon-distance#1]
You probably want to add this file to exclude node_modules and .rollup.cache

Those could be heavy and pointless to version

**Comment by chiotas** [comment]
Hi @vicb thanks for the feedback! I'm absolutely new to this word so quite unexpert! Not 101% sure of what to do but I'll try to do it :)

**Comment by chiotas** [comment]
Ok, file created to exclude node_modules and .rollup.cache
Thanks again!

**Comment by vicb** [comment]
> I'm absolutely new to this word so quite unexpert!

No worries, we all have been there at some point.

You also need to `git rm --cached node_modules` and `git rm --cached .rollup.cache` because they were added to git before you created the `.gitignore`.

The commands will delete the folders in the git but your local folders will be unaffected.

**Comment by chiotas** [comment]
Done! Thanks for the advice @vicb!
